### ISSUE TITLE
Clear button only works for randomized tiles.

### ISSUE THREAD

**Issue by mauriciosoares** [alanrsoares/redux-game-of-life#1]
Hey, I don't know if that's the expected behaviour, but when I click on "randomize" it creates a bunch of active tiles and if I click "clear", it cleans all of them.

But when I click in some tiles to active them, and then click on "clear", the tiles does not get cleaned.

Also if I active some tiles, and then randomize everything, and click in "clear" again, the tiles that I've created previously appears again.

You can check the gif...

![m9dldmkdes](https://cloud.githubusercontent.com/assets/2321259/9794984/976be32a-57c4-11e5-9369-e191f0b3520e.gif)

**Comment by alanrsoares** [comment]
Fixed. thanks for the heads up :smiley:
